package com.daypilot.domain.entity;

import com.daypilot.domain.enums.ApprovalStatus;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;

import java.time.Instant;
import java.util.UUID;

/**
 * A human-in-the-loop approval request for a consequential side-effect.
 *
 * <p>Created by the Approval Gateway when a task produces an action that
 * requires user sign-off (e.g. sending an email, creating an important
 * calendar event, deleting data). The approval stays in {@code PENDING}
 * state until the user approves, rejects, or the request expires.</p>
 *
 * <h3>Relationship: Approval to WorkflowTask (one-to-one)</h3>
 * <ul>
 *   <li><b>Owning side</b> &mdash; Approval holds the {@code task_id}
 *       foreign key. Same rationale as CalendarEvent: the approval is an
 *       optional child of the task.</li>
 *   <li><b>fetch = LAZY</b> &mdash; The Approval Gateway often queries
 *       pending approvals without needing the full task graph.</li>
 *   <li><b>optional = false</b> &mdash; Every approval must be linked
 *       to exactly one task.</li>
 *   <li><b>unique = true on JoinColumn</b> &mdash; Enforces at most one
 *       active approval per task at the database level.</li>
 *   <li><b>No cascade</b> &mdash; The Approval has its own lifecycle
 *       managed by the Approval Gateway, independent of task persistence.</li>
 * </ul>
 */
@Entity
@Table(name = "approvals")
public class Approval {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /** The task that requires approval for its side-effect. */
    @OneToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "task_id", nullable = false, unique = true)
    private WorkflowTask task;

    /** Current state of this approval request. */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private ApprovalStatus status;

    /**
     * Human-readable explanation of what the user is being asked to approve.
     * Generated by the agent or validation layer.
     */
    @Column(name = "request_summary", nullable = false, columnDefinition = "text")
    private String requestSummary;

    /**
     * Identifier of who resolved this approval (user ID, "system", etc.).
     * Null while the approval is still pending.
     */
    @Column(name = "resolved_by")
    private String resolvedBy;

    /** When the approval request was created. */
    @Column(name = "requested_at", nullable = false)
    private Instant requestedAt;

    /** When the approval was resolved. Null while pending. */
    @Column(name = "resolved_at")
    private Instant resolvedAt;

    // ------------------------------------------------------------------
    // Constructors
    // ------------------------------------------------------------------

    /** No-arg constructor required by JPA. */
    protected Approval() {
    }

    /**
     * Application constructor for creating a new approval request.
     *
     * @param task           the task requesting approval
     * @param status         initial status (typically {@code PENDING})
     * @param requestSummary human-readable description of the side-effect
     * @param requestedAt    when the request was created
     */
    public Approval(WorkflowTask task, ApprovalStatus status,
                    String requestSummary, Instant requestedAt) {
        this.task = task;
        this.status = status;
        this.requestSummary = requestSummary;
        this.requestedAt = requestedAt;
    }

    // ------------------------------------------------------------------
    // Accessors
    // ------------------------------------------------------------------

    public UUID getId() {
        return id;
    }

    public WorkflowTask getTask() {
        return task;
    }

    public void setTask(WorkflowTask task) {
        this.task = task;
    }

    public ApprovalStatus getStatus() {
        return status;
    }

    public void setStatus(ApprovalStatus status) {
        this.status = status;
    }

    public String getRequestSummary() {
        return requestSummary;
    }

    public void setRequestSummary(String requestSummary) {
        this.requestSummary = requestSummary;
    }

    public String getResolvedBy() {
        return resolvedBy;
    }

    public void setResolvedBy(String resolvedBy) {
        this.resolvedBy = resolvedBy;
    }

    public Instant getRequestedAt() {
        return requestedAt;
    }

    public Instant getResolvedAt() {
        return resolvedAt;
    }

    public void setResolvedAt(Instant resolvedAt) {
        this.resolvedAt = resolvedAt;
    }
}
